#!/bin/bash

IMG=cuda-sample-device-query-drv
EXE=deviceQueryDrv
LIBS=/usr/lib/x86_64-linux-gnu

if [ $1 == "build" ]; then
	docker build -t $IMG .
	exit
fi

if [ $1 == "run" ]; then
	docker run --rm --privileged \
		--volume=$LIBS/libcuda.so.1:$LIBS/libcuda.so.1 \
		$IMG
	exit
fi

if [ $1 == "shell" ]; then
	docker run -it --rm --privileged \
		--volume=$LIBS/libcuda.so.1:$LIBS/libcuda.so.1 \
		$IMG /bin/bash
	exit
fi

if [ $1 == "extract" ]; then
	if [ -z "$2" ]; then
		echo "Specify a file name to extract"
		exit 1
	fi
	CONT_ID=$(docker create $IMG)
	docker cp $CONT_ID:/usr/local/cuda/samples/1_Utilities/deviceQueryDrv/$2 .
	docker rm $CONT_ID
	exit
fi

if [ $1 == "strace" ]; then
	strace -o strace.log ./$EXE
	exit
fi

echo "Command not specified or unknown"
exit 1
