FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04

RUN apt update
RUN apt install -y file python-pip

# Many dependencies in tensorflow are listed as >= (e.g protobuf>=3.6.1)
# So when you download them in 2022, they are incompatibe with Python 2.7 anymore
# Install particular version manually to allow the TF package to find them locally
RUN pip2 install protobuf==3.6.1

#RUN pip2 install tensorflow==1.14.0
RUN pip2 install tensorflow-gpu==1.14.0

# Enable XLA (Accelerated Linear Algebra) https://www.tensorflow.org/xla
ENV TF_XLA_FLAGS=--tf_xla_cpu_global_jit

CMD bash
