#!/bin/bash

IMG=cuda-sample-device-query
EXE=deviceQuery
LIBS=/usr/lib/x86_64-linux-gnu

if [ $1 == "build" ]; then
	docker build -t $IMG .
	exit
fi

if [ $1 == "run" ]; then
	docker run --rm \
		--device=/dev/nvidia0:/dev/nvidia0 \
		--device=/dev/nvidiactl:/dev/nvidiactl \
		--device=/dev/nvidia-modeset:/dev/nvidia-modeset \
		--device=/dev/nvidia-uvm:/dev/nvidia-uvm \
		--device=/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools \
		--volume=$LIBS/libcuda.so.1:$LIBS/libcuda.so.1 \
		$IMG
	exit
fi

if [ $1 == "shell" ]; then
	docker run -it --rm \
		--device=/dev/nvidia0:/dev/nvidia0 \
		--device=/dev/nvidiactl:/dev/nvidiactl \
		--device=/dev/nvidia-modeset:/dev/nvidia-modeset \
		--device=/dev/nvidia-uvm:/dev/nvidia-uvm \
		--device=/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools \
		--volume=$LIBS/libcuda.so.1:$LIBS/libcuda.so.1 \
		$IMG /bin/bash
	exit
fi

if [ $1 == "extract" ]; then
	if [ -z "$2" ]; then
		echo "Specify a file name to extract"
		exit 1
	fi
	CONT_ID=$(docker create $IMG)
	docker cp $CONT_ID:/usr/local/cuda/samples/1_Utilities/deviceQuery/$2 .
	docker rm $CONT_ID
	exit
fi

if [ $1 == "strace" ]; then
	strace -o strace.log ./$EXE
	exit
fi

echo "Command not specified or unknown"
exit 1
